title: "Hello, I am Akash"
logo: "/images/akash.jpeg?raw=true"
description: >
  I am an enthusiast continuously working towards integrated intelligent systems.
  The key focus areas include robot system design and integration with sensors like Camera, Radar, GPS etc.

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
markdown: GFM
